DROP TABLE IF EXISTS colleges;

CREATE TABLE IF NOT EXISTS colleges
(
    college_id SERIAL PRIMARY KEY,
    college_name VARCHAR,
    college_location VARCHAR,
    general_web_addr VARCHAR,
    admissions_web_addr VARCHAR,
    fin_aid_web_addr VARCHAR,
    min_gpa FLOAT,
    max_gpa FLOAT,
    min_sat_read_write integer,
    max_sat_read_write integer,
    min_sat_math INTEGER,
    max_sat_math INTEGER,
    min_act INTEGER,
    max_act INTEGER,
    majors_web_addr VARCHAR,
    athletics_web_addr VARCHAR,
    sport_conference VARCHAR,
    completion_rate_athletes FLOAT,
    grad_rate_athletes FLOAT,
    questionaire_web_addr VARCHAR,
    faculty_student_ratio FLOAT,
    acceptance_rate FLOAT,
    race_ethnicity_stats_web_addr VARCHAR,
    gender_stats_web_addr VARCHAR,
    first_year_retention_rate FLOAT,
    first_year_transfer_rate FLOAT,
    first_year_grad_rate FLOAT,
    cost_tuition FLOAT,
    cost_total_est FLOAT,
    fin_aid_athlete_web_addr VARCHAR,
    academic_resources_web_addr VARCHAR,
    diversity_resources_web_addr VARCHAR,
    student_orgs_web_addr VARCHAR,
    study_abroad_web_addr VARCHAR,
    app_web_addr VARCHAR,
    app_essay_deadline DATE,
    app_letters_of_rec_deadline DATE,
    app_preferential_deadline DATE,
    app_fin_aid_deadline DATE,
    extra_notes VARCHAR
);

INSERT INTO colleges (
    college_name,
    college_location,
    general_web_addr,
    admissions_web_addr,
    fin_aid_web_addr,
    min_gpa,
    max_gpa,
    min_sat_read_write,
    max_sat_read_write,
    min_sat_math,
    max_sat_math,
    min_act,
    max_act,
    majors_web_addr,
    athletics_web_addr,
    sport_conference,
    completion_rate_athletes,
    grad_rate_athletes,
    questionaire_web_addr,
    faculty_student_ratio,
    acceptance_rate,
    race_ethnicity_stats_web_addr,
    gender_stats_web_addr,
    first_year_retention_rate,
    first_year_transfer_rate,
    first_year_grad_rate,
    cost_tuition,
    cost_total_est,
    fin_aid_athlete_web_addr,
    academic_resources_web_addr,
    diversity_resources_web_addr,
    student_orgs_web_addr,
    study_abroad_web_addr,
    app_web_addr,
    app_essay_deadline,
    app_letters_of_rec_deadline,
    app_preferential_deadline,
    app_fin_aid_deadline,
    extra_notes
)
VALUES  ('USC', 'Los Angeles', 'www.usc.edu', 'admissions.com', 'finaid.com', 2.0, 4.0, 400, 800, 400, 800, 28, 35, 'majors.com', 'athletics.com', 'PAC12', .75, .75, 'questionaire.com', .25, .12, 'racestats.com', 'genderstats.com', .8, .2, .8, 60000, 80000, 'finaidathlete.com', 'academicresources.com', 'diversityresources.com', 'studentorgs.com', 'studyabroad.com', 'application.com', '2023-12-31', '2024-01-15', '2023-11-10', '2023-12-31', 'USC is cool ig'),
        ('UCLA', 'Los Angeles', 'www.ucla.edu', 'admissions.com', 'finaid.com', 2.0, 4.0, 400, 800, 400, 800, 28, 35, 'majors.com', 'athletics.com', 'PAC12', .75, .75, 'questionaire.com', .25, .12, 'racestats.com', 'genderstats.com', .8, .2, .8, 60000, 80000, 'finaidathlete.com', 'academicresources.com', 'diversityresources.com', 'studentorgs.com', 'studyabroad.com', 'application.com', '2023-12-31', '2024-01-15', '2023-11-10', '2023-12-31', 'USC is cool ig');






